### ISSUE TITLE
Can't diff reports in tests anymore

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1273]
```
goroutine 9 [running]:
runtime.throw(0x8a60f0, 0x5)
        /usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc8205285a8 sp=0xc820528590
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:21 +0x1e4 fp=0xc8205285f8 sp=0xc8205285a8
github.com/weaveworks/scope/report.Counters.ForEach(0xc820016360, 0x99, 0xc820528760)
        /Users/twilkie/Documents/src/github.com/weaveworks/scope/report/counters.go:95 +0x50 fp=0xc8205286c0 sp=0xc8205285f8
github.com/weaveworks/scope/report.Counters.String(0xc820016360, 0x99, 0x0, 0x0)
        /Users/twilkie/Documents/src/github.com/weaveworks/scope/report/counters.go:112 +0x149 fp=0xc820528798 sp=0xc8205286c0
github.com/weaveworks/scope/report.(*Counters).String(0xc82038eda8, 0x0, 0x0)
        <autogenerated>:22 +0xa4 fp=0xc8205287d0 sp=0xc820528798
github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew.handleMethods(0xceed20, 0x1c00000, 0xc8200581c0, 0x85e700, 0xc82038eda8, 0x16, 0x0)
        /Users/twilkie/Documents/src/github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew/common.go:137 +0x6e8 fp=0xc8205288a8 sp=0xc8205287d0
github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc820529678, 0x8581a0, 0xc820016360, 0x99)
        /Users/twilkie/Documents/src/github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew/dump.go:308 +0x496 fp=0xc820528b48 sp=0xc8205288a8
github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc820529678, 0x876b60, 0xc820016340, 0x99)
        /Users/twilkie/Documents/src/github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew/dump.go:423 +0x18e4 fp=0xc820528de8 sp=0xc820528b48
github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc820529678, 0x7d94c0, 0xc8200c9380, 0x95)
        /Users/twilkie/Documents/src/github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew/dump.go:396 +0x123e fp=0xc820529088 sp=0xc820528de8
github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc820529678, 0x81e060, 0xc8200c9380, 0x99)
        /Users/twilkie/Documents/src/github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew/dump.go:423 +0x18e4 fp=0xc820529328 sp=0xc820529088
github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc820529678, 0x860d80, 0xc8200c9380, 0x99)
        /Users/twilkie/Documents/src/github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew/dump.go:423 +0x18e4 fp=0xc8205295c8 sp=0xc820529328
github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew.fdump(0xceed20, 0x1c00000, 0xc8200581c0, 0xc8205297f8, 0x1, 0x1)
        /Users/twilkie/Documents/src/github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew/dump.go:467 +0x2dc fp=0xc8205296b0 sp=0xc8205295c8
github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew.Sdump(0xc8205297f8, 0x1, 0x1, 0x0, 0x0)
        /Users/twilkie/Documents/src/github.com/weaveworks/scope/vendor/github.com/davecgh/go-spew/spew/dump.go:482 +0xaa fp=0xc820529730 sp=0xc8205296b0
github.com/weaveworks/scope/test.Diff(0x860d80, 0xc8200c9380, 0x860d80, 0xc8200c8a80, 0x0, 0x0)
        /Users/twilkie/Documents/src/github.com/weaveworks/scope/test/diff.go:15 +0xbf fp=0xc820529900 sp=0xc820529730
github.com/weaveworks/scope/test.Poll(0xc820380e10, 0x11e1a300, 0x860d80, 0xc8200c9380, 0xc820529c20)
        /Users/twilkie/Documents/src/github.com/weaveworks/scope/test/poll.go:26 +0x231 fp=0xc820529a50 sp=0xc820529900
github.com/weaveworks/scope/probe.TestProbe(0xc820380e10)
        /Users/twilkie/Documents/src/github.com/weaveworks/scope/probe/probe_internal_test.go:98 +0x60d fp=0xc820529f48 sp=0xc820529a50
testing.tRunner(0xc820380e10, 0xcf2cd8)
        /usr/local/go/src/testing/testing.go:473 +0x98 fp=0xc820529f80 sp=0xc820529f48
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820529f88 sp=0xc820529f80
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:582 +0x892

```

**Comment by tomwilkie** [comment]
This was caused by changes in go1.6 and fixed by https://github.com/davecgh/go-spew/commit/5215b55f46b2b919f50a1df0eaa5886afe4e3b3d
