### ISSUE TITLE
Panic in plugins registry.

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1282]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x640d89]

goroutine 94 [running]:
panic(0x164a080, 0xc820010090)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/weaveworks/scope/probe/plugins.(*Registry).ForEach(0x0, 0xc82075d990)
	/go/src/github.com/weaveworks/scope/probe/plugins/registry.go:151 +0x369
github.com/weaveworks/scope/probe/plugins.(*Registry).Report(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/weaveworks/scope/probe/plugins/registry.go:187 +0x96
github.com/weaveworks/scope/probe.(*Probe).report.func1(0xc8201432c0, 0xc820d949c0, 0x7fc09ad09188, 0x0)
	/go/src/github.com/weaveworks/scope/probe/probe.go:154 +0x106
created by github.com/weaveworks/scope/probe.(*Probe).report
	/go/src/github.com/weaveworks/scope/probe/probe.go:162 +0x135
```

**Comment by paulbellamy** [comment]
Was caused by a nil registry, due to `/var/run/scope/plugins` not being mounted. We should:
a) handle errors when launching the registry better
b) make the error `<probe> ERRO: 2016/04/13 09:38:22.429772 plugins: problem loading: no such file or directory` more informative.
