### ISSUE TITLE
'control' is leaking goroutines

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2002]
_From @rade on November 9, 2016 18:59_

observed in 'prod':
![screenshot from 2016-11-09 18-45-11](https://cloud.githubusercontent.com/assets/109109/20150386/8bdb04f8-a6ad-11e6-8159-6d386b01e342.png)

The 'control' containers are leaking go-routines at a steady rate; resulting in ~17k go-routines per container at the daily deploy.

Memory and CPU usage of these containers is low, FD usage is in the low hundreds and stable. AFAICT there is no user visible impact.

In dev the goroutine count is ~150 x 2 instances, after 18 hours of running. It tends to hover around one level for long periods and then increase before hovering again.

_Copied from original issue: weaveworks/service#1001_

**Comment by rade** [comment]
The container logs have this:
```
<app> ERRO: 2016/11/09 19:06:08.188973 websocket ping error: write tcp 10.244.250.5:80->10.244.253.45:38538: write: broken pipe
<app> ERRO: 2016/11/09 19:06:26.566592 websocket ping error: write tcp 10.244.250.5:80->10.244.252.40:57474: write: broken pipe
<app> ERRO: 2016/11/09 19:06:40.497616 websocket ping error: write tcp 10.244.250.5:80->10.244.253.45:37998: write: broken pipe
<app> ERRO: 2016/11/09 19:06:41.714949 websocket ping error: write tcp 10.244.250.5:80->10.244.253.45:44564: write: broken pipe
<app> ERRO: 2016/11/09 19:06:52.505588 websocket ping error: write tcp 10.244.250.5:80->10.244.253.45:46736: write: broken pipe
<app> ERRO: 2016/11/09 19:06:54.067502 websocket ping error: write tcp 10.244.250.5:80->10.244.253.45:53538: write: broken pipe
<app> ERRO: 2016/11/09 19:07:03.581781 websocket ping error: write tcp 10.244.250.5:80->10.244.252.40:42138: write: broken pipe
<app> ERRO: 2016/11/09 19:07:08.681132 websocket ping error: write tcp 10.244.250.5:80->10.244.254.38:48824: write: broken pipe
<app> ERRO: 2016/11/09 19:07:08.969659 websocket ping error: write tcp 10.244.250.5:80->10.244.253.45:37754: write: broken pipe
<app> ERRO: 2016/11/09 19:07:20.286530 websocket ping error: write tcp 10.244.250.5:80->10.244.254.38:36368: write: broken pipe
```

I grabbed some stack traces; there are lots of goroutines like this:
```
goroutine 152943 [semacquire, 238 minutes]:
sync.runtime_Semacquire(0xc424cbae0c)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc424cbae00)
        /usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/weaveworks/scope/app/multitenant.(*probeWorker).stop(0xc424cbade0)
        /go/src/github.com/weaveworks/scope/app/multitenant/sqs_control_router.go:314 +0x41
github.com/weaveworks/scope/app/multitenant.(*sqsControlRouter).Deregister(0xc42037d780, 0x219d180, 0xc4230a0900, 0xc42241df90, 0x10, 0x4285334ddc13073b, 0x0, 0x30)
        /go/src/github.com/weaveworks/scope/app/multitenant/sqs_control_router.go:298 +0xf7
github.com/weaveworks/scope/app.handleProbeWS.func1(0x219d180, 0xc4230a0900, 0x2198200, 0xc422d7e160, 0xc421e54e10)
        /go/src/github.com/weaveworks/scope/app/controls.go:102 +0x405
github.com/weaveworks/scope/app.requestContextDecorator.func1(0x2198200, 0xc422d7e160, 0xc421e54e10)
        /go/src/github.com/weaveworks/scope/app/router.go:46 +0x131
net/http.HandlerFunc.ServeHTTP(0xc420fdbd40, 0x2198200, 0xc422d7e160, 0xc421e54e10)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/weaveworks/scope/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420410190, 0x2198200, 0xc422d7e160, 0xc421e54e10)
        /go/src/github.com/weaveworks/scope/vendor/github.com/gorilla/mux/mux.go:107 +0x104
github.com/weaveworks/scope/common/middleware.Instrument.Wrap.func1(0x2198200, 0xc422d7e140, 0xc421e54e10)
        /go/src/github.com/weaveworks/scope/common/middleware/instrument.go:34 +0x1a2
net/http.HandlerFunc.ServeHTTP(0xc4216d0450, 0x2198200, 0xc422d7e140, 0xc421e54e10)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/weaveworks/scope/common/middleware.Log.Wrap.func1(0x2199d80, 0xc4222d0270, 0xc421e54e10)
        /go/src/github.com/weaveworks/scope/common/middleware/logging.go:24 +0x126
net/http.HandlerFunc.ServeHTTP(0xc4216d2020, 0x2199d80, 0xc4222d0270, 0xc421e54e10)
        /usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc420151080, 0x2199d80, 0xc4222d0270, 0xc421e54e10)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc422deda80, 0x219b200, 0xc422fcf140)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by rade** [comment]
AFAICT there is no code that calls `Done()` on that WaitGroup!  I reckon probeWorker.loop() is missing a `defer pw.done.Done()`. @2opremio looks like a scope bug; I guess we should move this issue.

**Comment by rade** [comment]
I've reproduced a steady goroutine growth in dev by running
```
for i in $(seq 1 100); do scope launch --service-token=<token> http://frontend.dev.weave.works; sleep 1; ./scope stop; done
```
![screenshot_2016-11-10_13-29-18](https://cloud.githubusercontent.com/assets/109109/20178565/ba7c44ce-a749-11e6-9acd-043f08387214.png)

In other words, stopping a probe leaks one goroutine per control container.
