### ISSUE TITLE
issues with docker daemon and stats in dev

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#2288]
_From @ekimekim on October 10, 2016 21:5_

it looks like the stats gathering is locked waiting on a response that never arrives

```
goroutine 92 [IO wait, 40 minutes]:
net.runtime_pollWait(0x7f53cb53a088, 0x72, 0xc821ca2000)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8217bc450, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8217bc450, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8217bc3f0, 0xc821ca2000, 0x1000, 0x1000, 0x0, 0x7f53ccd55050, 0xc820016120)
        /usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc821baa018, 0xc821ca2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc8217808a0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc8217808a0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:328 +0x21a
net/http/internal.readChunkLine(0xc8217808a0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/internal/chunked.go:110 +0x53
net/http/internal.(*chunkedReader).beginChunk(0xc821784510)
        /usr/local/go/src/net/http/internal/chunked.go:47 +0x39
net/http/internal.(*chunkedReader).Read(0xc821784510, 0xc821cb8000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/internal/chunked.go:77 +0xb7
net/http.(*body).readLocked(0xc820149900, 0xc821cb8000, 0x8000, 0x8000, 0x421636, 0x0, 0x0)
        /usr/local/go/src/net/http/transfer.go:651 +0xa1
net/http.(*body).Read(0xc820149900, 0xc821cb8000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transfer.go:643 +0x110
io.copyBuffer(0x7f53c9302850, 0xc8216680a0, 0x7f53cab8c1f8, 0xc820149900, 0xc821cb8000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:380 +0x247
io.Copy(0x7f53c9302850, 0xc8216680a0, 0x7f53cab8c1f8, 0xc820149900, 0xc820149900, 0x0, 0x0)
        /usr/local/go/src/io/io.go:350 +0x64
github.com/weaveworks/scope/vendor/github.com/fsouza/go-dockerclient.handleStreamResponse(0xc8217cc2d0, 0xc821780780, 0x0, 0x0)
        /go/src/github.com/weaveworks/scope/vendor/github.com/fsouza/go-dockerclient/client.go:598 +0x192
github.com/weaveworks/scope/vendor/github.com/fsouza/go-dockerclient.(*Client).stream(0xc820242280, 0x1b7ec08, 0x3, 0xc821780720, 
        /go/src/github.com/weaveworks/scope/vendor/github.com/fsouza/go-dockerclient/client.go:575 +0xc60
github.com/weaveworks/scope/vendor/github.com/fsouza/go-dockerclient.(*Client).Stats.func2(0xc820242280, 0xc8201b17c0, 0x40, 0xc82
        /go/src/github.com/weaveworks/scope/vendor/github.com/fsouza/go-dockerclient/container.go:990 +0x281
created by github.com/weaveworks/scope/vendor/github.com/fsouza/go-dockerclient.(*Client).Stats
        /go/src/github.com/weaveworks/scope/vendor/github.com/fsouza/go-dockerclient/container.go:1011 +0x27c
```

```
goroutine 166 [semacquire, 40 minutes]:
sync.runtime_Syncsemacquire(0xc821748100)
        /usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc8217480f0)
        /usr/local/go/src/sync/cond.go:63 +0x9b
io.(*pipe).read(0xc8217480c0, 0xc8217e0600, 0x200, 0x200, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:52 +0x2d2
io.(*PipeReader).Read(0xc821736040, 0xc8217e0600, 0x200, 0x200, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:134 +0x50
encoding/json.(*Decoder).refill(0xc8217de820, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc8217de820, 0x1, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:128 +0x413
encoding/json.(*Decoder).Decode(0xc8217de820, 0x14f7280, 0xc8217e2600, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:57 +0x159
github.com/weaveworks/scope/vendor/github.com/fsouza/go-dockerclient.(*Client).Stats(0xc820242280, 0xc821b24840, 0x40, 0xc821b2c96
        /go/src/github.com/weaveworks/scope/vendor/github.com/fsouza/go-dockerclient/container.go:1027 +0x406
github.com/weaveworks/scope/probe/docker.(*container).StartGatheringStats.func1(0x7f53c93027d0, 0xc820242280, 0xc821b24840, 0x40, 
        /go/src/github.com/weaveworks/scope/probe/docker/container.go:184 +0x4d
created by github.com/weaveworks/scope/probe/docker.(*container).StartGatheringStats
        /go/src/github.com/weaveworks/scope/probe/docker/container.go:187 +0x2b8
```

In this case, 40 minutes was the time since program start

_Copied from original issue: weaveworks/service#916_

**Comment by tomwilkie** [comment]
_From @rade on October 11, 2016 18:55_

how many of these goroutines were there?

btw, this issue should probably be moved to #weaveworks/scope.

**Comment by tomwilkie** [comment]
_From @rade on November 7, 2016 12:27_

cc @2opremio

**Comment by 2opremio** [comment]
It seems like the connection was hanging on the docker daemon side. Maybe https://github.com/docker/docker/issues/27772 ?

I cannot reproduce. Will reopen if it happens again.
