### ISSUE TITLE
Crash when listing DaemonSets

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#2537]
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc71c78]

goroutine 230 [running]:
panic(0x1514ac0, 0xc420018050)
/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/weaveworks/scope/vendor/k8s.io/kubernetes/pkg/client/cache.(*StoreToDaemonSetLister).List(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/weaveworks/scope/vendor/k8s.io/kubernetes/pkg/client/cache/listers.go:365 +0x68
github.com/weaveworks/scope/probe/kubernetes.(*client).WalkDaemonSets(0xc420126c00, 0xc4232e2a40, 0x0, 0x0)
/go/src/github.com/weaveworks/scope/probe/kubernetes/client.go:266 +0x47
github.com/weaveworks/scope/probe/kubernetes.(*Reporter).daemonSetTopology(0xc422ea2480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/weaveworks/scope/probe/kubernetes/reporter.go:304 +0x3f3
github.com/weaveworks/scope/probe/kubernetes.(*Reporter).Report(0xc422ea2480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/weaveworks/scope/probe/kubernetes/reporter.go:216 +0x168
github.com/weaveworks/scope/probe.(*Probe).report.func1(0xc420402870, 0xc42325f620, 0x23cd1a0, 0xc422ea2480)
/go/src/github.com/weaveworks/scope/probe/probe.go:155 +0x11c
created by github.com/weaveworks/scope/probe.(*Probe).report
/go/src/github.com/weaveworks/scope/probe/probe.go:165 +0xec

```

This was on Kubernetes 1.5.6

**Comment by 2opremio** [comment]
It seems like the `*StoreToDaemonSetLister` wasn't initialized.
