### ISSUE TITLE
100% CPU usage after closing pod log terminal

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#3033]
After closing a pod log terminal, the CPU usage of the probe on the host on which the pod resides jumps by 100% and stays there - looks like it's busy-looping on one core.

I've observed this in several environments, using Chrome and FF.

Container logs don't suffer from this.

Popping out the pod log terminal and then closing it does not trigger the problem.

All the probes I've tested with were 1.7.0. I also checked a cluster with 1.6.7 and the problem does _not_ occur there.

I suspect #3013 may have introduced this.

**Comment by rade** [comment]
I grabbed a go-routine dump from one of the spinning probes and found
```
goroutine 23452 [runnable]:
github.com/weaveworks/scope/probe/kubernetes.(*logReadCloser).Read(0xc4216ea8c0, 0xc421091000, 0x400, 0x400, 0x0, 0xc42105a600, 0xc421ffbd10)
        /go/src/github.com/weaveworks/scope/probe/kubernetes/logreadcloser.go:88 +0x365
go.(*struct { io.Reader; io.Writer }).Read(0xc4213415a0, 0xc421091000, 0x400, 0x400, 0x400, 0x0, 0x0)
        <autogenerated>:1 +0x5a
github.com/weaveworks/scope/common/xfer.(*pipe).CopyToWebsocket.func2(0x2f22780, 0xc4213415a0, 0xc421b41260, 0xc421275d50, 0x2f31880, 0xc421ffbd00)
        /go/src/github.com/weaveworks/scope/common/xfer/pipes.go:141 +0x9e
created by github.com/weaveworks/scope/common/xfer.(*pipe).CopyToWebsocket
        /go/src/github.com/weaveworks/scope/common/xfer/pipes.go:138 +0x1a8
```
Here's a theory: The channels in the [`select`](https://github.com/weaveworks/scope/blob/v1.7.0/probe/kubernetes/logreadcloser.go#L88) were closed by [`logReadCloser.Close`](https://github.com/weaveworks/scope/blob/v1.7.0/probe/kubernetes/logreadcloser.go#L111) and hence reading from them always succeeds.
