### ISSUE TITLE
TestRegistryEvents is flaky

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#311]
```
2015/07/08 11:32:42 docker container: collecting stats for ping
2015/07/08 11:32:42 docker container: error reading event io: read/write on closed pipe
2015/07/08 11:32:42 docker container: stopped collecting stats for ping
--- FAIL: TestRegistryEvents-4 (0.00s)
	registry_test.go:196: 
		--- want
		+++ have
		@@ -1,53 +1,3 @@
		-([]docker.Container) (len=2 cap=2) {
		- (*docker_test.mockContainer)(0xc2080ee018)({
		-  c: (*docker.Container)(0x14b4440)({
		-   ID: (string) (len=4) "ping",
		-   Created: (time.Time) 0001-01-01 00:00:00 +0000 UTC,
		-   Path: (string) "",
		-   Args: ([]string) <nil>,
		-   Config: (*docker.Config)(<nil>),
		-   State: (docker.State) Up 2562047h47m16.854775807s,
		-   Image: (string) (len=3) "baz",
		-   Node: (*docker.SwarmNode)(<nil>),
		-   NetworkSettings: (*docker.NetworkSettings)(<nil>),
		-   SysInitPath: (string) "",
		-   ResolvConfPath: (string) "",
		-   HostnamePath: (string) "",
		-   HostsPath: (string) "",
		-   Name: (string) (len=4) "pong",
		-   Driver: (string) "",
		-   Volumes: (map[string]string) <nil>,
		-   VolumesRW: (map[string]bool) <nil>,
		-   HostConfig: (*docker.HostConfig)(<nil>),
		-   ExecIDs: ([]string) <nil>,
		-   RestartCount: (int) 0,
		-   AppArmorProfile: (string) ""
		-  })
		- }),
		- (*docker_test.mockContainer)(0xc2080ee020)({
		-  c: (*docker.Container)(0x14b45c0)({
		-   ID: (string) (len=4) "wiff",
		-   Created: (time.Time) 0001-01-01 00:00:00 +0000 UTC,
		-   Path: (string) "",
		-   Args: ([]string) <nil>,
		-   Config: (*docker.Config)(<nil>),
		-   State: (docker.State) Up 2562047h47m16.854775807s,
		-   Image: (string) (len=3) "baz",
		-   Node: (*docker.SwarmNode)(<nil>),
		-   NetworkSettings: (*docker.NetworkSettings)(<nil>),
		-   SysInitPath: (string) "",
		-   ResolvConfPath: (string) "",
		-   HostnamePath: (string) "",
		-   HostsPath: (string) "",
		-   Name: (string) (len=4) "waff",
		-   Driver: (string) "",
		-   Volumes: (map[string]string) <nil>,
		-   VolumesRW: (map[string]bool) <nil>,
		-   HostConfig: (*docker.HostConfig)(<nil>),
		-   ExecIDs: ([]string) <nil>,
		-   RestartCount: (int) 0,
		-   AppArmorProfile: (string) ""
		-  })
		- })
		+([]docker.Container) {
		 }
		 
FAIL
```

**Comment by tomwilkie** [comment]
```
2015/07/08 12:10:08 docker container: collecting stats for ping
2015/07/08 12:10:08 docker container: error reading event io: read/write on closed pipe
2015/07/08 12:10:08 docker container: stopped collecting stats for ping
panic: test timed out after 10s

goroutine 19 [running]:
testing.func·008()
	/usr/local/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive]:
testing.RunTests(0x9de188, 0x14b3e40, 0x5, 0x5, 0xc208078401)
	/usr/local/go/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc208030550, 0x14bf660)
	/usr/local/go/src/testing/testing.go:485 +0xe1
main.main()
	github.com/weaveworks/scope/probe/docker/_test/_testmain.go:114 +0x382

goroutine 17 [chan send]:
github.com/weaveworks/scope/probe/docker_test.(*mockDockerClient).send(0xc2080e8060, 0xc2080ce2c0)
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:92 +0x104
github.com/weaveworks/scope/probe/docker_test.func·012()
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:190 +0x1d3
github.com/weaveworks/scope/probe/docker_test.setupStubs(0xc2080e8060, 0xc2080f2750)
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:130 +0x1dc
github.com/weaveworks/scope/probe/docker_test.TestRegistryEvents(0xc208080120)
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:238 +0x102
testing.tRunner(0xc208080120, 0x14b3e70)
	/usr/local/go/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xd4e

goroutine 18 [semacquire]:
sync.(*Mutex).Lock(0xc2080e8060)
	/usr/local/go/src/sync/mutex.go:66 +0xfd
github.com/weaveworks/scope/probe/docker_test.(*mockDockerClient).ListImages(0xc2080e8060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:65 +0x6e
github.com/weaveworks/scope/probe/docker.(*registry).updateImages(0xc2080f8000, 0x0, 0x0)
	github.com/weaveworks/scope/probe/docker/_test/_obj_test/registry.go:206 +0xf5
github.com/weaveworks/scope/probe/docker.(*registry).listenForEvents(0xc2080f8000, 0x0)
	github.com/weaveworks/scope/probe/docker/_test/_obj_test/registry.go:128 +0x4a9
github.com/weaveworks/scope/probe/docker.(*registry).loop(0xc2080f8000)
	github.com/weaveworks/scope/probe/docker/_test/_obj_test/registry.go:90 +0x6e
created by github.com/weaveworks/scope/probe/docker.NewRegistry
	github.com/weaveworks/scope/probe/docker/_test/_obj_test/registry.go:74 +0x38b
FAIL	github.com/weaveworks/scope/probe/docker	10.017s
ok  	github.com/weaveworks/scope/probe/endpoint	0.022s	coverage: 53.7% of statements
ok  	github.com/weaveworks/scope/probe/host	0.017s	coverage: 78.3% of statements
ok  	github.com/weaveworks/scope/probe/overlay	0.017s	coverage: 67.7% of statements
ok  	github.com/weaveworks/scope/probe/process	0.016s	coverage: 89.4% of statements
ok  	github.com/weaveworks/scope/render	0.030s	coverage: 91.7% of statements
ok  	github.com/weaveworks/scope/report	0.145s	coverage: 62.4% of statements
```

**Comment by tomwilkie** [comment]
```
2015/07/08 12:54:57 docker container: collecting stats for ping
2015/07/08 12:54:57 docker container: error reading event io: read/write on closed pipe
2015/07/08 12:54:57 docker container: stopped collecting stats for ping
==================
WARNING: DATA RACE
Read by goroutine 11:
  runtime.mapaccess1_faststr()
      /usr/local/go/src/runtime/hashmap_fast.go:179 +0x0
  github.com/weaveworks/scope/probe/docker_test.(*mockDockerClient).InspectContainer()
      /home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:61 +0x92
  github.com/weaveworks/scope/probe/docker.(*registry).addContainer()
      github.com/weaveworks/scope/probe/docker/_test/_obj_test/registry.go:246 +0xc7
  github.com/weaveworks/scope/probe/docker.(*registry).updateContainers()
      github.com/weaveworks/scope/probe/docker/_test/_obj_test/registry.go:194 +0x276
  github.com/weaveworks/scope/probe/docker.(*registry).listenForEvents()
      github.com/weaveworks/scope/probe/docker/_test/_obj_test/registry.go:121 +0x321
  github.com/weaveworks/scope/probe/docker.(*registry).loop()
      github.com/weaveworks/scope/probe/docker/_test/_obj_test/registry.go:90 +0x6d

Previous write by goroutine 10:
  runtime.mapassign1()
      /usr/local/go/src/runtime/hashmap.go:376 +0x0
  github.com/weaveworks/scope/probe/docker_test.func·014()
      /home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:195 +0x1bd
  github.com/weaveworks/scope/probe/docker_test.setupStubs()
      /home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:130 +0x1db
  github.com/weaveworks/scope/probe/docker_test.TestRegistryEvents()
      /home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:233 +0x101
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:447 +0x133

Goroutine 11 (running) created at:
  github.com/weaveworks/scope/probe/docker.NewRegistry()
      github.com/weaveworks/scope/probe/docker/_test/_obj_test/registry.go:74 +0x38b
  github.com/weaveworks/scope/probe/docker_test.func·014()
      /home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:182 +0x5a
  github.com/weaveworks/scope/probe/docker_test.setupStubs()
      /home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:130 +0x1db
  github.com/weaveworks/scope/probe/docker_test.TestRegistryEvents()
      /home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:233 +0x101
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:447 +0x133

Goroutine 10 (running) created at:
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:555 +0xd4e
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:485 +0xe0
  main.main()
      github.com/weaveworks/scope/probe/docker/_test/_testmain.go:114 +0x381
==================
panic: test timed out after 10s

goroutine 8 [running]:
testing.func·008()
	/usr/local/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive]:
testing.RunTests(0x9de808, 0x14b4e40, 0x5, 0x5, 0xc208078401)
	/usr/local/go/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc208030550, 0x14c0660)
	/usr/local/go/src/testing/testing.go:485 +0xe1
main.main()
	github.com/weaveworks/scope/probe/docker/_test/_testmain.go:114 +0x382

goroutine 33 [chan send]:
github.com/weaveworks/scope/probe/docker_test.(*mockDockerClient).send(0xc2080e0060, 0xc2080c4100)
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:92 +0x104
github.com/weaveworks/scope/probe/docker_test.func·014()
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:197 +0x282
github.com/weaveworks/scope/probe/docker_test.setupStubs(0xc2080e0060, 0xc2080ec750)
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:130 +0x1dc
github.com/weaveworks/scope/probe/docker_test.TestRegistryEvents(0xc2080e2000)
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:233 +0x102
testing.tRunner(0xc2080e2000, 0x14b4e70)
	/usr/local/go/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xd4e

goroutine 34 [semacquire]:
sync.(*Mutex).Lock(0xc2080e0060)
	/usr/local/go/src/sync/mutex.go:66 +0xfd
github.com/weaveworks/scope/probe/docker_test.(*mockDockerClient).ListImages(0xc2080e0060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:65 +0x6e
github.com/weaveworks/scope/probe/docker.(*registry).updateImages(0xc2080f0000, 0x0, 0x0)
	github.com/weaveworks/scope/probe/docker/_test/_obj_test/registry.go:206 +0xf5
github.com/weaveworks/scope/probe/docker.(*registry).listenForEvents(0xc2080f0000, 0x0)
	github.com/weaveworks/scope/probe/docker/_test/_obj_test/registry.go:128 +0x4a9
github.com/weaveworks/scope/probe/docker.(*registry).loop(0xc2080f0000)
	github.com/weaveworks/scope/probe/docker/_test/_obj_test/registry.go:90 +0x6e
created by github.com/weaveworks/scope/probe/docker.NewRegistry
	github.com/weaveworks/scope/probe/docker/_test/_obj_test/registry.go:74 +0x38b
FAIL	github.com/weaveworks/scope/probe/docker	10.015s
```
