### ISSUE TITLE
http: panic serving 172.16.0.3:55686: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#480]
I'm seeing this quite often in my logs:

```
2015/09/14 03:56:21 http: panic serving 172.16.0.3:55686: runtime error: invalid memory address or nil pointer dereference
goroutine 194 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
compress/gzip.(*Reader).Close(0x0, 0x0, 0x0)
	/usr/local/go/src/compress/gzip/gunzip.go:287 +0x6c
main.func·008()
	/home/vagrant/src/github.com/weaveworks/scope/app/router.go:85 +0x39
main.func·009(0x7fd3033c3f10, 0xc2081434a0, 0xc2082fe340)
	/home/vagrant/src/github.com/weaveworks/scope/app/router.go:93 +0x230
net/http.HandlerFunc.ServeHTTP(0xc208130990, 0x7fd3033c3f10, 0xc2081434a0, 0xc2082fe340)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20800ce60, 0x7fd3033c3f10, 0xc2081434a0, 0xc2082fe340)
	/home/vagrant/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.(*ServeMux).ServeHTTP(0xc20803a870, 0x7fd3033c3f10, 0xc2081434a0, 0xc2082fe340)
	/usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc2080625a0, 0x7fd3033c3f10, 0xc2081434a0, 0xc2082fe340)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208143040)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
```

**Comment by tomwilkie** [comment]
According to the docs (http://golang.org/pkg/net/http/#Request):
```
// The Server will close the request body. The ServeHTTP
// Handler does not need to.
```

Seems to be coming from us closing the body on the server when the gzip decoding fails.  Don't know why its failing, but we don't need to close the body.
