### ISSUE TITLE
Docker test timeout

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#514]
https://circleci.com/gh/weaveworks/scope/1399
```
panic: test timed out after 8m0s

goroutine 33 [running]:
testing.func·008()
	/usr/local/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 5 minutes]:
testing.RunTests(0xb39688, 0x1651ae0, 0x6, 0x6, 0xc208066801)
	/usr/local/go/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc2080480f0, 0x165dbe0)
	/usr/local/go/src/testing/testing.go:485 +0xe1
main.main()
	github.com/weaveworks/scope/probe/docker/_test/_testmain.go:144 +0x384

goroutine 17 [chan send, 5 minutes]:
github.com/weaveworks/scope/probe/docker_test.(*mockDockerClient).send(0xc2080ce000, 0xc20812c000)
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:95 +0x104
github.com/weaveworks/scope/probe/docker_test.func·015()
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:231 +0x891
github.com/weaveworks/scope/probe/docker_test.setupStubs(0xc2080ce000, 0xc2080a9f50)
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:152 +0x1dc
github.com/weaveworks/scope/probe/docker_test.TestRegistryEvents(0xc208108000)
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:257 +0x33e
testing.tRunner(0xc208108000, 0x1651b28)
	/usr/local/go/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xd4e

goroutine 18 [semacquire, 5 minutes]:
sync.(*RWMutex).Lock(0xc2080ce000)
	/usr/local/go/src/sync/rwmutex.go:87 +0xca
github.com/weaveworks/scope/probe/docker_test.(*mockDockerClient).RemoveEventListener(0xc2080ce000, 0xc208104120, 0x0, 0x0)
	/home/ubuntu/src/github.com/weaveworks/scope/probe/docker/registry_test.go:81 +0x67
github.com/weaveworks/scope/probe/docker.func·003()
	github.com/weaveworks/scope/probe/docker/_obj/registry.go:114 +0xce
github.com/weaveworks/scope/probe/docker.(*registry).addContainer(0xc20810a000, 0xa316d0, 0x4, 0x0, 0x0)
	github.com/weaveworks/scope/probe/docker/_obj/registry.go:259 +0x20a
github.com/weaveworks/scope/probe/docker.(*registry).handleEvent(0xc20810a000, 0xc2080327c0)
	github.com/weaveworks/scope/probe/docker/_obj/registry.go:237 +0x1fa
github.com/weaveworks/scope/probe/docker.(*registry).listenForEvents(0xc20810a000, 0x0)
	github.com/weaveworks/scope/probe/docker/_obj/registry.go:141 +0x756
github.com/weaveworks/scope/probe/docker.(*registry).loop(0xc20810a000)
	github.com/weaveworks/scope/probe/docker/_obj/registry.go:90 +0x6e
created by github.com/weaveworks/scope/probe/docker.NewRegistry
	github.com/weaveworks/scope/probe/docker/_obj/registry.go:74 +0x38b
FAIL	
```

**Comment by peterbourgon** [comment]
Just came here to report this.

**Comment by tomwilkie** [comment]
Link to failure?

**Comment by peterbourgon** [comment]
https://circleci.com/gh/weaveworks/scope/1470

**Comment by tomwilkie** [comment]
Not seen this in a long time; pls reopen if you see again.
