### ISSUE TITLE
Panic running master against service

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#792]
Reported in #785:

```
goroutine 46 [running]:
github.com/weaveworks/scope/xfer.(*JSONWebsocketCodec).ReadRequestHeader(0xc8202afe00, 0xc8202afe20, 0x0, 0x0)
        /go/src/github.com/weaveworks/scope/xfer/controls.go:143 +0xa7
net/rpc.(*Server).readRequestHeader(0xc8208eff40, 0x7fa207562820, 0xc8202afe00, 0x0, 0x0, 0xc8202afe20, 0x41ae00, 0x0, 0x0)
        /usr/local/go/src/net/rpc/server.go:576 +0x90
net/rpc.(*Server).readRequest(0xc8208eff40, 0x7fa207562820, 0xc8202afe00, 0xc8206fe180, 0x416f1e, 0x1e1b230, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/rpc/server.go:543 +0x8b
net/rpc.(*Server).ServeCodec(0xc8208eff40, 0x7fa207562820, 0xc8202afe00)
        /usr/local/go/src/net/rpc/server.go:462 +0x8c
github.com/weaveworks/scope/xfer.(*appClient).controlConnection(0xc82011eb00, 0x4f9700, 0x0, 0x0)
        /go/src/github.com/weaveworks/scope/xfer/app_client.go:217 +0x482
github.com/weaveworks/scope/xfer.(*appClient).(github.com/weaveworks/scope/xfer.controlConnection)-fm(0xc800000008, 0x0, 0x0)
        /go/src/github.com/weaveworks/scope/xfer/app_client.go:225 +0x2e
github.com/weaveworks/scope/xfer.(*appClient).doWithBackoff(0xc82011eb00, 0x1397400, 0x8, 0xc82011bf58)
        /go/src/github.com/weaveworks/scope/xfer/app_client.go:170 +0x9e
github.com/weaveworks/scope/xfer.(*appClient).ControlConnection.func1(0xc82011eb00)
        /go/src/github.com/weaveworks/scope/xfer/app_client.go:225 +0x22d
created by github.com/weaveworks/scope/xfer.(*appClient).ControlConnection
        /go/src/github.com/weaveworks/scope/xfer/app_client.go:226 +0x35
```

**Comment by tomwilkie** [comment]
My bad; the intention was the the controls would be backward compatible, but this change was left in from an old prototype of pipes that used the same ws for pipe IOs.

Its hard to think of a way of supporting both versions here - I'll give it a go, but we might just have to fix the panic and accept that controls are broken v10 <-> v11.
